minio:
  accessKey: minio
  secretKey: minio123
  bucket: leadnews
  endpoint: http://192.168.179.200:9000
  #endpoint: http://192.168.88.130:9000
  readPath: http://192.168.179.200:9000
  #readPath: http://192.168.88.130:9000
  enable: true #开启使用Minio 对应LeadNewsAutoConfig中的@ConditionalOnProperty注解属性
